server:
  port: 7001
app:
  name: User Service

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserDB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  